# Generated by Django 5.1.3 on 2024-11-20 13:24

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.TextField(null=True)),
                ('language', models.CharField(default='FR', max_length=2)),
                ('status', models.BooleanField(default=False)),
                ('win_pong', models.IntegerField(default=0)),
                ('lose_pong', models.IntegerField(default=0)),
                ('win_tictactoe', models.IntegerField(default=0)),
                ('lose_tictactoe', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_score', models.IntegerField(default=0)),
                ('adv_score', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('date', models.DateTimeField(null=True)),
                ('start_match', models.DateTimeField(null=True)),
                ('end_match', models.DateTimeField(null=True)),
                ('adv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adv_matches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
