# Generated by Django 5.1.3 on 2024-11-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.TextField(null=True)),
                ('language', models.CharField(default='FR', max_length=2)),
                ('status', models.BooleanField(default=False)),
                ('win_pong', models.IntegerField(default=0)),
                ('lose_pong', models.IntegerField(default=0)),
                ('win_tictactoe', models.IntegerField(default=0)),
                ('lose_tictactoe', models.IntegerField(default=0)),
            ],
        ),
    ]
